<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SanRestful\Module'                             => __DIR__ . '/Module.php',
    'SanRestful\Controller\SampleClientController'  => __DIR__ . '/src/SanRestful/Controller/SampleClientController.php',
    'SanRestful\Controller\SampleRestfulController' => __DIR__ . '/src/SanRestful/Controller/SampleRestfulController.php',
);